from typing import List

required_plan: List[str] = [
    "CATALOGUE START DAY", "CATALOGUE START MONTH", "CATALOGUE START YEAR",
    "CATALOGUE END DAY", "CATALOGUE END MONTH", "CATALOGUE END YEAR",
    "CATALOGUE DESCRIPTION"
]

required_holiday: List[str] = [
    "DAY", "MONTH", "YEAR"
]

required_stage1: List[str] = [
    'ATTRIBUTE MARKETING','GOLD CODE','LV','LU','SUPPLIER CODE','COMMERCIAL CONTRACT','PURCHASE NETWORK',
    'GOLD PROMO NETWORK','NORMAL PURCHASE PRICE','DISCOUNT (% OR VALUE)','DELIVERY TYPE',
    'PP START DAY','PP START MONTH','PP START YEAR','PP END DAY','PP END MONTH','PP END YEAR',
    '% DELIVERY 1','% DELIVERY 2','% DELIVERY 3','FREE PRODUCT'
]

required_stage2: List[str] = [
    'GOLD CODE', 'LV', 'SV', 'TILLCODE', 'SV DESCRIPTION', 'NORMAL SALE PRICE', 'PROMOTION SALE PRICE',
    'PRICELIST', 'SALE VAT'
]

required_src: List[str] = [
    'NO', 'ATTRIBUTE MARKETING', 'STRUCTURE', 'GOLD CODE', 'LV', 'LU', 'PCB', 'VIETNAMESE DESCRIPTION', 
    'SUPPLIER CODE', 'SUPPLIER NAME', 'COMMERCIAL CONTRACT', 'PURCHASE NETWORK', 'GOLD PROMO NETWORK', 
    'NORMAL PURCHASE PRICE', 'NORMAL DISCOUNT ON PURCHASE (%)', 'NET PURCHASE PRICE', 'DISCOUNT (% OR VALUE)', 
    'CLAIM', 'BUYER CHECK', 'PROMOTION PURCHASE PRICE', 'PURCHASE VAT', 'DELIVERY TYPE', 'PP START DAY', 
    'PP START MONTH', 'PP START YEAR', 'PP END DAY', 'PP END MONTH', 'PP END YEAR', '% DELIVERY 1', 
    '% DELIVERY 2', '% DELIVERY 3', 'SV', 'TILLCODE', 'SV DESCRIPTION', 'NORMAL SALE PRICE', 
    'PROMOTION SALE PRICE', 'PRICELIST', 'SALE REGION', 'SALE VAT', '% NORMAL MARGIN', '% PROMOTIONAL MARGIN', 
    '% DISCOUNT ON SALE PRICE', 'FREE PRODUCT', 'PROPO QTY', 'FORECASTS TOTAL TURNOVER VIETNAM  ', 'CHOSEN QUANTITY', 'MULTI'
]

required_cm: List[str] = [
    'NO', 'ATTRIBUTE MARKETING', 'GOLD CODE', 'LV', 'LU', 'PCB', 'VIETNAMESE DESCRIPTION',
    'SUPPLIER CODE', 'SUPPLIER NAME', 'COMMERCIAL CONTRACT', 'PURCHASE NETWORK', 'GOLD PROMO NETWORK', 
    'NORMAL PURCHASE PRICE', 'NORMAL DISCOUNT ON PURCHASE (%)', 'NET PURCHASE PRICE', 'DISCOUNT (% OR VALUE)', 
    'CLAIM', 'BUYER CHECK', 'PROMOTION PURCHASE PRICE', 'PURCHASE VAT', 'PP START DAY', 'PP START MONTH', 
    'PP START YEAR', 'PP END DAY', 'PP END MONTH', 'PP END YEAR', 'SV', 'TILLCODE', 'SV DESCRIPTION', 
    'NORMAL SALE PRICE', 'PROMOTION SALE PRICE', 'PRICELIST', 'SALE VAT', 'SALE REGION', '% NORMAL MARGIN', 
    '% PROMOTIONAL MARGIN', '% DISCOUNT ON SALE PRICE', 'DELIVERY TYPE', '% DELIVERY 1', '% DELIVERY 2', 
    '% DELIVERY 3', 'FREE PRODUCT', 'PROPO QTY', 'FORECASTS TOTAL TURNOVER VIETNAM  ', 'CHOSEN QUANTITY', 'MULTI'
]

required_network: List[str] = [
    'SITE','NATIONAL_SITE','GROUP_SITE','REGION_SITE', 'ACTIVE'
]

date_columns_plan: List[str] = ['CATALOGUE START DATE',
       'CATALOGUE END DATE', 'PC SEND DATA', 'PC SEND DELETE CODE',
       'SHOP ACTIVE START', 'SHOP ACTIVE END',
       'PC SEND THE PURCHASE PRICE ADJUSTMENT', 'GENERAL PO DATE (D-17)',
       'STORE PRINT PO (D-16)', 'VINAMILK | ORDER DATE 1',
       'DIRECT | ORDER DATE 1', 'CROSS-DOCKING | ORDER DATE 1',
       'VINAMILK | ORDER DATE 2', 'DIRECT | ORDER DATE 2',
       'CROSS-DOCKING | ORDER DATE 2', 'VINAMILK | ORDER DATE 3',
       'DIRECT | ORDER DATE 3', 'CROSS-DOCKING | ORDER DATE 3',
       'DELIVERY DATE 1', 'DELIVERY DATE 2', 'DELIVERY DATE 3']

department: List[str] = [
    '110', '120', '160', '210', '220', '230', '240', '250', '260', '310', '320', '330', '340', '350', '360', 
    '410', '420', '430', '440', '450', '460', '470', '480', '510', '520', '530', '540', '550', '580', 
    '610', '620', '630', '640', '650', '710', '720', '910', '920', '930', '950', '980', '990', 
    '2110', '2120', '2160', '2210', '2220', '2230', '2240', '2250', '2260', '2310', '2320', '2340', '2350', 
    '2360', '2410', '2420', '2430', '2440', '2450', '2460', '2470', '2480', '2510', '2520', '2530', '2540', 
    '2550', '2560', '2590', '2810', '2820', '2830', '2840', '2850', '2860'
]

VAT = {
    '0%':'3',
    '5%':'1',
    '8%':'5',
    '10%':'2',
    'KKKT':'9',
    'KCT':'0'
}
